# Generated by Django 5.1 on 2024-08-08 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_basket_options_alter_basketitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product",
                to="products.category",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
    ]
